<?php

//require_once '../../User/Model.php';
//require_once '../../User/View.php';
require_once(dirname(__FILE__) . '/../../User/Model.php');
require_once(dirname(__FILE__) . '/../../User/View.php');
require_once(dirname(__FILE__) . '/../../User/Controller.php');

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-07-11 at 11:34:17.
 */
class ControllerTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Controller
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Controller;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Controller::analyseRoute
     * @todo   Implement testAnalyseRoute().
     */
    public function testAnalyseRoute() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Controller::directRoute
     * @todo   Implement testDirectRoute().
     */
    public function testDirectRoute() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Controller::routeError
     * @todo   Implement testRouteError().
     */
    public function testRouteError() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Controller::defaultPage
     * @todo   Implement testDefaultPage().
     */
    public function testDefaultPage() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Controller::updateUser
     * @todo   Implement testUpdateUser().
     */
    public function testUpdateUser() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Controller::createUser
     * @todo   Implement testCreateUser().
     */
    public function testCreateUser() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Controller::deleteUser
     * @todo   Implement testDeleteUser().
     */
    public function testDeleteUser() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Controller::readUser
     * @todo   Implement testReadUser().
     */
    public function testReadUser() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Controller::indexUser
     * @todo   Implement testIndexUser().
     */
    public function testIndexUser() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Controller::getID
     * @todo   Implement testGetID().
     */
    public function testGetID() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Controller::getParams
     * @todo   Implement testGetParams().
     */
    public function testGetParams() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Controller::getQueryParams
     * @todo   Implement testGetQueryParams().
     */
    public function testGetQueryParams() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Controller::getErrors
     * @todo   Implement testGetErrors().
     */
    public function testGetErrors() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
