<?php

// @TODO namespace

//require_once '../../User/Model.php';
//require_once '../../User/View.php';
require_once(dirname(__FILE__) . '/../../User/Model.php');
require_once(dirname(__FILE__) . '/../../User/View.php');
require_once(dirname(__FILE__) . '/../../User/Controller.php');

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-07-11 at 11:34:17.
 */
class ControllerTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Controller
     */
    protected $object;
    
    /**
     * @var Array of routes 
     */
    protected $routes;
    
    /**
     * @var Array of routeParameters
     */
    protected $routesParams;
    
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Controller;
        
        // Define routes to test.
        $this->routes = [
            '/index.php?command=read&id=6',
            '/index.php?command=delete&id=4',
            '/index.php?command=create&e=e@test.dev&fn=first1&ln=last1&p=password1',
            '/index.php?command=index',
            '/index.php?command=read&id=6&type=json',
            '/index.php?command=index&type=json',
            '/index.php?command=NoCommand',
            '/index.php?command=update&e=e@test.dev&fn=first1&ln=last1&p=password1&id=6',
            '/read/id/6',
            '/read/id/6/type/json',
            '/update/e/e@test.dev/fn/first1/ln/last1/p/password1/id/6',
            '/delete/id/6',
            '/NoRoute',
            '/create/e/e@test.dev/fn/first1/ln/last1/p/password1',
            '/index',
            '/index/type/json',
            '/index.php',
        ];
        
        // Define analysed routes as expected output.
        $this->routesParams = [
            ['command' => 'read', 'query' => ['command' => 'read', 'id' => '6']],
            ['command' => 'delete', 'query' => ['command' => 'delete', 'id' => '4']],
            ['command' => 'create', 'query' => 
                ['command' => 'create', 'e' => 'e@test.dev', 'fn' => 'first1', 'ln' => 'last1', 'p' => 'password1']],
            ['command' => 'index', 'query' => ['command' => 'index']],
            ['command' => 'read', 'query' => ['command' => 'read', 'id' => '6', 'type' => 'json']],
            ['command' => 'index', 'query' => ['command' => 'index', 'type' => 'json']],
            ['command' => 'NoCommand', 'query' => ['command' => 'NoCommand']],
            ['command' => 'update', 'query' => 
                ['command' => 'update', 'e' => 'e@test.dev', 'fn' => 'first1', 'ln' => 'last1', 'p' => 'password1', 'id' => '6']],
            ['command' => 'read', 'query' => ['id' => '6']],
            ['command' => 'read', 'query' => ['id' => '6', 'type' => 'json']],
            ['command' => 'update', 'query' => 
                ['e' => 'e@test.dev', 'fn' => 'first1', 'ln' => 'last1', 'p' => 'password1', 'id' => '6']],
            ['command' => 'delete', 'query' => ['id' => '6']],
            ['command' => 'NoRoute', 'query' => []],
            ['command' => 'create', 'query' => 
                ['e' => 'e@test.dev', 'fn' => 'first1', 'ln' => 'last1', 'p' => 'password1']],
            ['command' => 'index', 'query' => []],
            ['command' => 'index', 'query' => ['type' => 'json']],
            ['command' => '', 'query' => []],
        ];
        
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
    }

    /**
     * Controller test analyseRoute
     */
    public function testAnalyseRoute() {
        // Test all routes and expected outputs.
        for ($i = 0; $i < count($this->routes); $i++) {
            $expected = $this->routesParams[$i];
            
            // Analyse the route.
            $url = $this->routes[$i];
            $results = $this->object->analyseRoute($url);
            
            // Segment route into params and/or id.
            $params = $this->object->getParams();
            $id = $this->object->getID();
            $query = $this->object->getQueryParams();

            // Check that are the same.
            $this->assertEquals($params, $expected);
            $this->assertEquals($query, $expected['query']);
            $this->assertInternalType('boolean', $results);
        }
    }

    /**
     * Controller test directRoute
     */
    public function testDirectRoute() {
         // Test all routes and expected outputs.
        for ($i = 0; $i < count($this->routes); $i++) {
            $expected = $this->routesParams[$i];
            
            // Get URL (path).
            $url = $this->routes[$i];
            
            // Collect output when routes are tested.
            ob_start();
            $results = $this->object->directRoute($url);
            $text = ob_get_clean();
            
            // Segment route into params and/or id.
            $params = $this->object->getParams();
            $id = $this->object->getID();
            $query = $this->object->getQueryParams();
            
            // Check results
            $this->assertEquals($params, $expected);
            $this->assertEquals($query, $expected['query']);
            $this->assertInternalType('string', $text);
        }
    }

    /**
     * Controller test routeError
     */
    public function testRouteError() {
        ob_start();
        $results = $this->object->routeError();
        $text = ob_get_clean();
        $this->assertInternalType('string', $text);
        $this->assertInternalType('boolean', $results);
        $this->assertEquals(false, $results);
    }

    /**
     * Controller test defaultPage
     */
    public function testDefaultPage() {
        ob_start();
        $results = $this->object->defaultPage();
        $text = ob_get_clean();
        $this->assertInternalType('string', $text);
        $this->assertInternalType('boolean', $results);
        $this->assertEquals(true, $results);
    }

    /**
     * Controller test updateUser
     * 
     * @TODO improve this test
     */
    public function testUpdateUser() {
        // Set up a read route.
        $url = '/update/e/e@test.dev/fn/first1/ln/last1/p/password1/id/6';
        $results = $this->object->analyseRoute($url);
        
        // Separaate the parameters
        $params = $this->object->getParams();
        $query = $this->object->getQueryParams();
        
        // Udpdate a user, and capture output.
        ob_start();
        $createdId = $this->object->createUser($params);
        $text = ob_get_clean();

        // Check the results
        $this->assertEquals($params, ['command' => 'update', 'query' => 
                ['e' => 'e@test.dev', 'fn' => 'first1', 'ln' => 'last1', 'p' => 'password1', 'id' => '6']]);
        $this->assertInternalType('string', $text);
        $this->assertInternalType('boolean', $results);
        $this->assertEquals(true, $results);
    }

    /**
     * Controller test createUser
     * 
     * @TODO Improve this test.
     */
    public function testCreateUser() {
        // Set up a read route.
        $url = '/create/e/e@test.dev/fn/first1/ln/last1/p/password1';
        $results = $this->object->analyseRoute($url);
        
        // Separaate the parameters
        $params = $this->object->getParams();
        $query = $this->object->getQueryParams();
        
        // Create the user, and capture output.
        ob_start();
        $createdId = $this->object->createUser($params);
        $text = ob_get_clean();

        // Check the results
        $this->assertEquals($params, ['command' => 'create', 'query' => 
                ['e' => 'e@test.dev', 'fn' => 'first1', 'ln' => 'last1', 'p' => 'password1']]);
        $this->assertInternalType('string', $text);
        $this->assertInternalType('boolean', $results);
        $this->assertEquals(true, $results);
        
        // Delete the created user.
        ob_start();
        $this->object->deleteUser($createdId);
        $text = ob_get_clean();
    }

    /**
     * Controller test deleteUser
     * 
     * @TODO improve testing for deleteUser
     */
    public function testDeleteUser() {
        // Set up a read route.
        $url = '/delete/id/0';
        $results = $this->object->analyseRoute($url);
        
        // Delete the user, and capture output.
        ob_start();
        $results = $this->object->deleteUser(0);
        $text = ob_get_clean();

        // Separaate the parameters
        $params = $this->object->getParams();
        $id = $this->object->getID();
        $query = $this->object->getQueryParams();

        // Check the results
        $this->assertEquals($params, ['command' => 'delete', 'query' => ['id' => '0']]);
        $this->assertEquals($id, 0);
        $this->assertEquals($query, ['id' => '0']);
        $this->assertInternalType('string', $text);
        $this->assertInternalType('boolean', $results);
        $this->assertEquals(false, $results);
    }

    /**
     * Controller test readUser
     * 
     * @TODO make better tests for readUser.
     */
    public function testReadUser() {
        // Set up a read route.
        $url = '/read/id/0';
        $results = $this->object->analyseRoute($url);
        
        // Read the user, and capture output.
        ob_start();
        $results = $this->object->readUser();
        $text = ob_get_clean();

        // Separaate the parameters
        $params = $this->object->getParams();
        $id = $this->object->getID();
        $query = $this->object->getQueryParams();

        // Check the results
        $this->assertEquals($params, ['command' => 'read', 'query' => ['id' => '0']]);
        $this->assertEquals($id, 0);
        $this->assertEquals($query, ['id' => '0']);
        $this->assertInternalType('string', $text);
        $this->assertInternalType('boolean', $results);
        $this->assertEquals(false, $results);
    }

    /**
     * Controller test indexUser
     */
    public function testIndexUser() {
        ob_start();
        $results = $this->object->indexUser();
        $text = ob_get_clean();
        $this->assertInternalType('array', $results);
        $this->assertInternalType('string', $text);
    }

    /**
     * Controller test getID
     */
    public function testGetID() {
        $result = $this->object->getID();
        $expected = false;
        $this->assertEquals($expected, $result);
    }

    /**
     * Controller test getParams
     */
    public function testGetParams() {
        $result = $this->object->getParams();
        $expected = NULL;
        $this->assertEquals($expected, $result);
    }

    /**
     * Controller test getQueryParams
     */
    public function testGetQueryParams() {
        $result = $this->object->getQueryParams();
        $expected = NULL;
        $this->assertEquals($expected, $result);
    }
    
    /**
     * Controller test getUser
     */
    public function testGetUser() {
        // Make sure class returned is the Model class.
        $result = $this->object->getUser();
        $this->assertInstanceOf(Model::class, $result);
    }

    /**
     * Controller test getErrors
     */
    public function testGetErrors() {
        // Add errors and check if they are show up.
        $this->object->getUser()->addError('err1');
        $this->object->getUser()->addError('err2');
        $result = $this->object->getErrors();
        $expected = [0 => 'err1', 1 => 'err2'];
        $this->assertEquals($expected, $result, "\$canonicalize = true", $delta = 0.0, $maxDepth = 10, $canonicalize = true);
    }

}
